In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("token_usage.csv")

In [3]:
df["task_id"] = df["task_id"].replace("20250215-120903", "survery Large Language Model papers")

In [4]:
df

,prompt_tokens,completion_tokens,cached_tokens,task_id,model
0,9891,527,0,20250215-120638,gpt-4o-mini
1,1816,258,0,20250215-120638,gpt-4o-2024-11-20
2,3548,106,0,20250215-120638,gpt-4o-2024-11-20
3,9559,466,0,20250215-120638,gpt-4o-mini
4,9891,558,0,survery Large Language Model papers,gpt-4o-mini
...,...,...,...,...,...
386,5370,76,0,2_recipes_chinese,gpt-4o-2024-11-20
387,2972,92,0,2_recipes_chinese,gpt-4o-2024-11-20
388,2190,146,0,2_recipes_chinese,gpt-4o-2024-11-20
389,1390,6,0,2_recipes_chinese,gpt-4o-2024-11-20
390,759,173,0,2_recipes_chinese,gpt-4o-2024-11-20

In [5]:
s = df.groupby(by=["task_id","model"]).sum()

In [6]:
type(s)

pandas.core.frame.DataFrame

In [7]:
s= s.reset_index(drop=False)

In [8]:
s

,task_id,model,prompt_tokens,completion_tokens,cached_tokens
0,1_bakery_birthday_cake,gpt-4o-2024-11-20,21700,686,0
1,1_bakery_birthday_cake,gpt-4o-mini,26847,1439,0
2,1_late_night_korean_food,gpt-4o-2024-11-20,351869,13742,0
3,1_late_night_korean_food,gpt-4o-mini,381906,18734,0
4,1_nearest_bakery,gpt-4o-2024-11-20,22589,625,0
5,1_nearest_bakery,gpt-4o-mini,41919,2188,0
6,1_thai_duck,gpt-4o-2024-11-20,255280,10780,0
7,1_thai_duck,gpt-4o-mini,241430,11616,0
8,20250215-120638,gpt-4o-2024-11-20,5364,364,0
9,20250215-120638,gpt-4o-mini,19450,993,0
10,2_llm_agents_survey,gpt-4o-2024-11-20,143199,5184,0
11,2_llm_agents_survey,gpt-4o-mini,102244,4879,0
12,2_recipes_chinese,gpt-4o-2024-11-20,45650,1516,0
13,2_recipes_chinese,gpt-4o-mini,45162,2175,0
14,2_segment_anything_cited,gpt-4o-2024-11-20,182018,6398,0
15,2_segment_anything_cited,gpt-4o-mini,136187,6468,0
16,survery Large Language Model papers,gpt-4o-2024-11-20,121959,6170,0
17,survery Large Language Model papers,gpt-4o-mini,83124,4032,0

In [9]:
def cost_function(row):
    if (row["model"] == "gpt-4o-mini"):
        return row["prompt_tokens"]* 0.15/1000000.0 + 0.6 /1000000.0 * row["completion_tokens"]
    else:
        return row["prompt_tokens"]* 2.5/1000000.0 + 10.0 /1000000.0 * row["completion_tokens"]

In [10]:
s["cost"] = s.apply(cost_function, axis= 1)

In [11]:
s

,task_id,model,prompt_tokens,completion_tokens,cached_tokens,cost
0,1_bakery_birthday_cake,gpt-4o-2024-11-20,21700,686,0,0.061110
1,1_bakery_birthday_cake,gpt-4o-mini,26847,1439,0,0.004890
2,1_late_night_korean_food,gpt-4o-2024-11-20,351869,13742,0,1.017092
3,1_late_night_korean_food,gpt-4o-mini,381906,18734,0,0.068526
4,1_nearest_bakery,gpt-4o-2024-11-20,22589,625,0,0.062723
5,1_nearest_bakery,gpt-4o-mini,41919,2188,0,0.007601
6,1_thai_duck,gpt-4o-2024-11-20,255280,10780,0,0.746000
7,1_thai_duck,gpt-4o-mini,241430,11616,0,0.043184
8,20250215-120638,gpt-4o-2024-11-20,5364,364,0,0.017050
9,20250215-120638,gpt-4o-mini,19450,993,0,0.003513
10,2_llm_agents_survey,gpt-4o-2024-11-20,143199,5184,0,0.409838
11,2_llm_agents_survey,gpt-4o-mini,102244,4879,0,0.018264
12,2_recipes_chinese,gpt-4o-2024-11-20,45650,1516,0,0.129285
13,2_recipes_chinese,gpt-4o-mini,45162,2175,0,0.008079
14,2_segment_anything_cited,gpt-4o-2024-11-20,182018,6398,0,0.519025
15,2_segment_anything_cited,gpt-4o-mini,136187,6468,0,0.024309
16,survery Large Language Model papers,gpt-4o-2024-11-20,121959,6170,0,0.366598
17,survery Large Language Model papers,gpt-4o-mini,83124,4032,0,0.014888

In [12]:
s["cost"].sum()

np.float64(3.5219747500000005)

In [13]:
s2 = s.loc[[2,3,6,7,10,11,12,13,14,15,16,17]]

In [14]:
s2 = s2.copy().reset_index(drop=True)

In [16]:
s2.to_csv("testreport.csv")